services:
  # api: 
  #   image: cal-api
  #   build: .
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     db:
  #       condition: service_healthy
  db:
    image: mysql:8
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # volumes:
    #   - ./dbdata:/var/lib/mysql/

# volumes:
#   dbdata:
