services:
  api: 
    image: cal-backend
    build: ./blyat
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    # TODO: make this smaller size? is smaller even better?
    image: mysql:8
    ports:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # volumes:
    #   - ./dbdata:/var/lib/mysql/

# volumes:
#   dbdata:
